[project]
name = "evm-algorand"
version = "1.0.0"
description = "evm-algorand integration for cross-chain swaps"

[project.contracts]
escrow = { name = "FusionEscrow", path = "contracts/escrow.py" }
solver = { name = "FusionSolver", path = "contracts/solver.py" }
pool = { name = "FusionPool", path = "contracts/pool.py" }

[project.networks]
testnet = { name = "testnet", algod = "https://testnet-api.algonode.cloud", indexer = "https://testnet-idx.algonode.cloud" }
mainnet = { name = "mainnet", algod = "https://mainnet-api.algonode.cloud", indexer = "https://mainnet-idx.algonode.cloud" }

[project.deployments]
testnet = { name = "testnet", network = "testnet" }
mainnet = { name = "mainnet", network = "mainnet" }

[project.accounts]
deployer = { name = "deployer", description = "Account used for deploying contracts" }
alice = { name = "alice", description = "Alice's account for testing" }
carol = { name = "carol", description = "Carol's account for testing" }

[project.localnet]
name = "localnet"
algod = "http://localhost:4001"
kmd = "http://localhost:4002"
indexer = "http://localhost:8980"

[project.deploy]
testnet = [
    "algokit project deploy escrow --network testnet",
    "algokit project deploy solver --network testnet", 
    "algokit project deploy pool --network testnet"
]
mainnet = [
    "algokit project deploy escrow --network mainnet",
    "algokit project deploy solver --network mainnet",
    "algokit project deploy pool --network mainnet"
] 