# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: manx393@gmail.com
author_name: monyverse
contract_name: contractsdemo
deployment_language: python
preset_name: production
project_name: algotest-contracts

